steps:
  - label: "Building the mondo repo"
    plugins:
      - monebag/monorepo-diff#v2.5.8:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "mondorepo/frontend/"
              config:
                command: "./mondorepo/frontent/build.sh"
            - path: "mondorepo/backend/"
              config:
                command: "./mondorepo/backend/build.sh"
    agents:
      queue: ubuntus
