steps:
  - label: "Building the mondo repo"
    env:
      BUILDKITE_MONDO_PATH: mondorepo
    plugins:
      - monebag/monorepo-diff#v2.5.8:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "${BUILDKITE_MONDO_PATH}/frontend/"
              config:
                command: "./${BUILDKITE_MONDO_PATH}/frontend/build.sh"
            - path: "${BUILDKITE_MONDO_PATH}/backend/"
              config:
                command: "./${BUILDKITE_MONDO_PATH}/backend/build.sh"
    agents:
      queue: ubuntus
